load ../debug.maude
load ../specs/tas.maude
load ../full-maude-lite.maude
load ../utils.maude

red extractType(upModule('TAS-CHECK, true), 'init) .
red extractType(upModule('TAS-CHECK, true), 'lofree) .
red isModule('TAS-FAKE) .
red isModule('TAS-CHECK) .
red buildTerm('init, extractType(upModule('TAS-CHECK, true), 'init)) .
red buildTerm('lofree, extractType(upModule('TAS-CHECK, true), 'lofree)) .

red getAllSuccessors(upModule('TAS-CHECK, false), 'init.Config, 'X:Config) .
red genSeqs(upModule('TAS-CHECK, false), 'init.Config, 'X:Config, 1) .
red checkSat(upModule('TAS-CHECK, false), 'init.Config, 'inWs1.Prop) .
red checkSat(upModule('TAS-CHECK, false), 'init.Config, '~_['inWs1.Prop]) .
red genSeqs(upModule('TAS-CHECK, false), 'init.Config, 'X:Config, 2) .