set trace off .
--- set trace whole on .
--- set trace eq off .
--- set trace condition off .
--- set trace substitution off .
--- set trace rewrite off .
--- set trace select on .
set print attribute on .
set show timing on .
set print conceal on .
print conceal fmod_is_sorts_.____endfm
              mod_is_sorts_._____endm
              db
              if_then_else_fi
              tableau:_
              node2id:_
              id2node:_
              .