version: "3.7"

services:
    app:
        image: leadsto
        build:
            context: .
            dockerfile: dockerfile
        working_dir: /app
        volumes:
            - ./:/app
        stdin_open: true
        tty: true
        mem_limit: 2G