mod DCA2MC-PARSING is
    pr FM-TERMSET .
    pr MOVE-DOWN .

    vars T T' : Term .
    
    --- parse the module qid
    op parseHeader : Term -> Qid .
    eq parseHeader('token[T]) = downQid(T) .
    eq parseHeader('_`{_`}['token[T], T']) = downQid(T) .

    --- get term from token and bubble
    op solveBubbleAndToken : Term -> Term .
    eq solveBubbleAndToken('token[T]) = T .
    eq solveBubbleAndToken('bubble[T]) = T .
endm